services:
  app-base:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        BACKEND: ${BACKEND:-rocm}       # rocm or cpu
        ROCM_VER: ${ROCM_VER:-7.2.1}
        UV_EXTRA: ${UV_EXTRA:-rocm72}   # rocm72 or cpu
        UV_VERSION: ${UV_VERSION:-0.8.15}
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./references:/app/references
    environment:
      COMPILE: ${COMPILE:-0}
    tty: true
    stdin_open: true
